### ISSUE TITLE
review and revise function names

### ISSUE THREAD

**Issue by mbjones** [laurenmh/codyn#29]
The current function names are good, but might be improved for clarity and intuitiveness.  By checking this before the package is released, we will make it easier for people to understand each function and its purpose.  We should also check if these function names are already in use in other CRAN packages.  The current function names from the NAMESPACE export file to be checked are:

- [x] VR
- [x] calVR
- [x] calVR2
- [x] calVRrealnull
- [x] calnullVR
- [x] genRand
- [x] meanrank
- [x] nullVRCI
- [x] pairwise_turnover
- [x] timelag
- [x] synchrony
- [x] synch_onerep
- [x] calComDat -> rename to transpose_community()
- [x] calComTS -> deleted function

Check each off once we have agreement to keep the function name.

**Comment by mbjones** [comment]
We should also reconsider the names for the data transpose utilities:

- [ ] calComDat() --> transpose_community()
- [ ] calComTS() --> time_series_community()

I find the original names opaque (particularly the 'cal' prefix), and would prefer something more descriptive, like listed above.

Objections? Alternatives?

**Comment by laurenmh** [comment]
I agree and like transpose_community()


I'm pretty sure we can delete calComTS() entirely, it was needed for the
variance ratio phase scrambling but Andrew and I decided that wasn't
necessary to include, the temporal torus-translation is sufficient.

**Comment by mbjones** [comment]
OK, sounds good.  I will rename the function to transpose_community() throughout, and will delete calComTS() altogether.  Do you also think there is a need for check_names(), which isn't called in any of the other functions? But it is used in the tests.   If we need to keep it, should it be moved to the tests?  And should it be renamed to something more specific and accurate?

**Comment by laurenmh** [comment]
check_names is a recent addition by @aammd  

I think his idea was to include it in the wrapper for each function to make it check that the column names people specify in function arguments in fact exist in the dataframe. Let's check and see if he had further plans for its use, or if there are other ways to do a similar test.

**Comment by mbjones** [comment]
calComDat() was renamed to transpose_community() in sha 562e2c92 .

**Comment by laurenmh** [comment]
For synchrony metric, might replace "Loreau" and "Gross" with more descriptive metric names (indecisive, since they both call their metric synchrony and don't want to use the symbol)...

**Comment by mbjones** [comment]
Finished renaming functions.
