### ISSUE TITLE
tests for synchrony metrics

### ISSUE THREAD

**Issue by mbjones** [laurenmh/codyn#30]
Need tests for synchrony metrics.  I added a stub test file, but the meat of the test needs to be completed.

**Comment by laurenmh** [comment]
For the "Gross" metric, need to determine and accommodate the proper way to handle situations in which a species doesn't vary at all over the time series. Currently gives a warning that the std dev is zero, and returns an NA.

For example, using the KNZ_001d data, subplot D_5, salvia azurea has an abundance of 3 across the time series, and so returns an NA.

**Comment by danfbflynn** [comment]
If using Gross metric, now there is a test for species which do not vary in abundance over time within a sample (subplot). If so, issues a warning and omits that species from the focal species list.
