### ISSUE TITLE
Resolve any issues reported by R CMD check

### ISSUE THREAD

**Issue by sbpcs59** [laurenmh/codyn#40]

**Comment by sbpcs59** [comment]
All issues identified by devtools::check() have been resolved except for:
* checking R code for possible problems ... NOTE
community_stability: no visible binding for global variable ‘stability’

This looks like a simple problem from community_stability.R, line 19, maybe one of the
authors could fix this.

Also, running check on Max OSX (I'm on 10.9.5) produces this error:
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
LaTeX errors found:
! LaTeX Error: File `inconsolata.sty' not found.

This appears to be an error with the library 'texinfo @5.2.2' that is incompatible with R, and has been an issue for awhile. This error does not occur on Ubuntu 14.04, so this appears to be an issue with R and
not the codyn package. If you are interested, the problem is described here:

http://markmail.org/search/?q=list%3Aorg.r-project.r-devel+inconsolata.sty#query:list%3Aorg.r-project.r-devel%20inconsolata.sty+page:1+mid:arxwlgn5jkvzpibd+state:results

**Comment by jarioksa** [comment]
Actually, `R CMD check --as-cran`  gives three new `NOTE`s which all are easy to fix.

In the first case check even gives the solution: capitalize initial letters
```
The Title field should be in title case, current version then in title case:
‘Community dynamics metrics’
‘Community Dynamics Metrics’
```
Second is more cryptic: you have to mean that in R "complete sentence" means any string ending with full stop (period). See https://stat.ethz.ch/pipermail/r-help/2015-July/430057.html . This also got into Twitter.
```
* checking DESCRIPTION meta-information ... NOTE
Malformed Description field: should contain one or more complete sentences.
```
These were old things, but new R also wants you to explicitly import packages in **stats**, **graphics** etc. Fortunately the new check also gives you the text you need to add to your `NAMESPACE`:
```
Undefined global functions or variables:
  aggregate as.formula cor cov lm quantile sd stability var
Consider adding
  importFrom("stats", "aggregate", "as.formula", "cor", "cov", "lm",
             "quantile", "sd", "var")
to your NAMESPACE.
```
This adds several new unknown names in addition to `stability`.

The coding of  `stability` is really opaque, though. I had to look code for a long time before noticing that you referred to a column in `output`. I would consider more transparent coding.

Please do not use `is.na(stability) == F` but use instead `!is.na(stability)`.

**Comment by mbjones** [comment]
Fixed all issues with non-ASCII characters in doc files.

**Comment by mbjones** [comment]
Confirmed that all checks are working on:

- [ ] Mac OS X 10.3.3, R 3.2.2
- [ ] Mac OS X 10.3.3, R-devel
- [ ] Ubuntu 14.04, R 3.2.2
- [ ] Ubuntu 14.04, R-devel
- [ ] Windows 7 SP 1, R 3.2.2
- [ ] Windows 7 SP 1, R-devel

**Comment by mbjones** [comment]
All checks resolved.
