### ISSUE TITLE
ensure data frames are ordered before unlisting

### ISSUE THREAD

**Issue by mbjones** [laurenmh/codyn#58]
Current functions unlist without ensuring order of observations, which can cause indeterminate results.  Order them first.

**Comment by mbjones** [comment]
Fixed in sha 669965d9190e0bc29c3a7c5f026a5ccb191b6ca2 . @laurenmh, can you confirm this is ready to go and close the ticket?

**Comment by laurenmh** [comment]
added tests for all functions
