### ISSUE TITLE
adjustments to coding consistency 

### ISSUE THREAD

**Issue by aammd** [laurenmh/codyn#63]
Reviewer comments:

> Firstly there is inconsistency in the application of a coding style. In a number of the source files I noticed inconsistent spacing around operators, and in some instances it was lacking altogether. Making the code more readable by putting spacing around all or key operators (notably `<-`) would be a distinct improvement. 

Perhaps the easiest way to resolve this is to manually check all files:

- [ ] community_stability.R
- [ ] turnover.R
- [ ] codyn-package.R
- [ ] utilities.R
- [ ] rank_shift.R
- [ ] rate_change.R
- [ ] temporal_torus_translation.R
- [ ] synchrony.R
- [ ] variance_ratio.R

recent builds of Rstudio will highlight inconsistent code style. Also, i've heard some people enjoy [lintr](https://github.com/jimhester/lintr) for validating R code -- does anyone prefer that approach?

**Comment by laurenmh** [comment]
added spacing around key operators; leaving this open to do a full check after other changes are made

**Comment by aammd** [comment]
I fixed this up where I could in #67 ; after merging somebody should probably take another pass through the code
