### ISSUE TITLE
Add S3 class for cyclic_shift

### ISSUE THREAD

**Issue by aammd** [laurenmh/codyn#66]
Reviewer comment (paraphrased): 

> It would be more user friendly to implement functions in a more object-oriented way [...] arrange for `temporal_torus_translation()` (or a suitably renamed alternative, see #65  ) to return an object of a stated class, say `"cyclic_shift"`, and then provide the confidence interval functionality via a method for the `confint()` S3 generic via function `confint.cyclic_shift()`. 

This means that `cyclic_shift()` would end up doing most of the permutation work:

>  have `cyclic_shift()` do the actual permuting and return the permutation *p* value, as well as the vector of permuted test statistics. Then the `confint()` method would take this vector of permuted test statistic values and apply the required `quantile()` to generate confidence intervals for null distribution.

I'm excited about this suggestion; I think it will lead to more modular, cleaner code.

**Comment by laurenmh** [comment]
Hey Andrew, Glad you're excited about this one. I started shifting from torus to cyclic and restructuring the code, but would appreciate you focusing on this one.

Currently cyclic_shift will return a numeric vector of null model test statistics (the number specified by bootnumber). 

confint.cyclic_shift returns the CI. I haven't switched to saving as S3 objects/using confint. When you do, we need to retain the three potential scenarios:
1) replicate.var = NA. Here, just return CI for the single replicate (your changes start line 72 in temporal_torus_translation)

2) replicate.var = *specified* and average.replicates ==T. Here, we average the values from each replicate (as in line 87) = need CI on the resulting vector (changes start at line 88).

3) replicate.var = *specified* and average.replicates == F. Here, need a CI for each replicate (change start at line 96).
